### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by BH-M87** [uber-web/loaders.gl#340]
I met this problem, it caused by sometimes the process is not undefined but the process.version is undefined, in @loaders.gl/core/dist/esm/utils/globals.js:45, `process.version.match` will cause this problem.
Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined at Module. <anonymous> (http://localhost:8000/vendors.async.js:19546:65) at Module../node_modules/@loaders.gl_core@1.2.1@@loaders.gl/core/dist/esm/utils/globals.js (http://localhost:8000/vendors.async.js:19549:30) at webpack_require (http://localhost:8000/umi.js:775:30) at fn (http://localhost:8000/umi.js:130:20) at Module../node_modules/@loaders.gl_core@1.2.1@@loaders.gl/core/dist/esm/javascript-utils/stream-utils.js (http://localhost:8000/vendors.async.js:17622:72) at webpack_require (http://localhost:8000/umi.js:775:30) at fn (http://localhost:8000/umi.js:130:20) at Module../node_modules/@loaders.gl_core@1.2.1@@loaders.gl/core/dist/esm/lib/loader-utils/get-data.js (http://localhost:8000/vendors.async.js:18590:88) at webpack_require (http://localhost:8000/umi.js:775:30) at fn (http://localhost:8000/umi.js:130:20) at Module../node_modules/@loaders.gl_core@1.2.1@@loaders.gl/core/dist/esm/lib/parse-with-loader.js (http://localhost:8000/vendors.async.js:18906:80) at webpack_require (http://localhost:8000/umi.js:775:30) at fn (http://localhost:8000/umi.js:130:20) at Module../node_modules/@loaders.gl_core@1.2.1@@loaders.gl/core/dist/esm/lib/parse.js (http://localhost:8000/vendors.async.js:19111:76) at webpack_require (http://localhost:8000/umi.js:775:30) at fn (http://localhost:8000/umi.js:130:20) at Module../node_modules/@loaders.gl_core@1.2.1@@loaders.gl/core/dist/esm/index.js (http://localhost:8000/vendors.async.js:16703:68) at webpack_require (http://localhost:8000/umi.js:775:30) at fn (http://localhost:8000/umi.js:130:20) at Module../node_modules/@deck.gl_core@7.2.2@@deck.gl/core/dist/esm/lib/init.js (http://localhost:8000/vendors.async.js:7703:74) at webpack_require (http://localhost:8000/umi.js:775:30) at fn (http://localhost:8000/umi.js:130:20) at Module../node_modules/@deck.gl_core@7.2.2@@deck.gl/core/dist/esm/index.js (http://localhost:8000/vendors.async.js:3622:67) at webpack_require (http://localhost:8000/umi.js:775:30) at fn (http://localhost:8000/umi.js:130:20) at Module../node_modules/@deck.gl_react@7.2.2@@deck.gl/react/dist/esm/deckgl.js (http://localhost:8000/vendors.async.js:16227:71) at webpack_require (http://localhost:8000/umi.js:775:30) at fn (http://localhost:8000/umi.js:130:20) at Module../node_modules/@deck.gl_react@7.2.2@@deck.gl/react/dist/esm/index.js (http://localhost:8000/vendors.async.js:16410:65) at webpack_require (http://localhost:8000/umi.js:775:30) at fn (http://localhost:8000/umi.js:130:20) at Module../src/pages/entry/components/Map/MapGL.jsx (http://localhost:8000/p__testMap__index.async.js:19:72) at webpack_require (http://localhost:8000/umi.js:775:30) at fn (http://localhost:8000/umi.js:130:20) at Module../src/pages/testMap/index.js (http://localhost:8000/p__testMap__index.async.js:97:90) at webpack_require (http://localhost:8000/umi.js:775:30) at fn (http://localhost:8000/umi.js:130:20)

**Comment by ibgreen** [comment]
@BH-M87 Thanks for reporting and fixing! 

Do you need a new npm version published with the fix? Are you using loaders.gl v1.2?

PS - Out of curiosity, which environment are you using that sets `process` but not `process.version`?

**Comment by BH-M87** [comment]
@ibgreen I notice that the problem has been fixed in next version, that's cool.
I use it with umijs, and in this environment, this problem happened.

**Comment by ibgreen** [comment]
@BH-M87 thanks for following up. 

Any other feedback on loaders.gl, how it could be more useful, let us know!
